/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import lombok.val;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {

    @Test
    @DisplayName("getToken は Token を返すこと")
    void whenGetToken_thenReturnsToken() {
        val lexer = new MyLexer();
        var result = lexer.getToken("if (x==1)");
        var expected = createGetTokenResult("if");
        assertEquals(expected, result);
    }

    @Test
    @DisplayName("getToken は Token を返すこと")
    void whenGetToken_thenReturnsToken2() {
        val lexer = new MyLexer();
        var result = lexer.getToken("if (x==1)", 2);
        var expected = createGetTokenResult("(", 3);
        assertEquals(expected, result);
    }

    @Test
    @DisplayName("getToken は Token を返すこと")
    void whenGetToken_thenReturnsToken3() {
        val lexer = new MyLexer();
        var result = lexer.getToken("x==1)", 0);
        var expected = createGetTokenResult(TokenType.Symbol, "x", 0);
        assertEquals(expected, result);
    }

    private GetTokenResult createGetTokenResult(String s, int start) {
        val x = switch (s) {
            case "if" -> TokenType.If;
            case "(" -> TokenType.OpenParen;
            default -> TokenType.Unknown;
        };
        return new GetTokenResult(new Token(x, s), start + s.length());
    }

    private GetTokenResult createGetTokenResult(String s) {
        return createGetTokenResult(s, 0);
    }

    private GetTokenResult createGetTokenResult(TokenType type, String value, int start) {
        return new GetTokenResult(new Token(type, value), start + value.length());
    }
}
